# Generated by Django 4.2.11 on 2026-07-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_value_transaction_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='descption',
        ),
    ]
