# Generated by Django 4.2.11 on 2026-07-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_name_transaction_descption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='conta',
            new_name='account',
        ),
    ]
