# Generated by Django 4.2.11 on 2026-07-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_conta_transaction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='descption',
            new_name='description',
        ),
    ]
